version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./kalah-db/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nathanpirral@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  kalah-frontend:
    container_name: kalah-frontend
    image: kalah-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
        - kalah-backend

  kalah-backend:
    container_name: kalah-backend
    image: kalah-backend
    networks:
      - postgres
    ports:
        - "8080:8080"
    restart: unless-stopped
    depends_on:
        - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: